name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/demo-copilot-04:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/demo-copilot-04:latest

    - name: Deploy to Azure Container App
      run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          
          az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

          az containerapp up \
          --name demo-copilot-04-app \
          --resource-group demo-copilot-04-rg \
          --image ghcr.io/${{ github.repository_owner }}/demo-copilot-04:latest \
          --registry-server ghcr.io \
          --registry-username ${{ github.actor }} \
          --registry-password ${{ secrets.PAT }}

    # - name: Test
    #   run: dotnet test --no-build
