name: Terraform Provision

on:
  push:
    paths:
      - 'iac/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Provision
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Initialize Terraform
      working-directory: ./iac
      run: terraform init

    - name: Validate Terraform
      working-directory: ./iac
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./iac
      run: terraform plan

    - name: Apply Terraform
      working-directory: ./iac
      run: terraform apply -auto-approve
